### ISSUE TITLE
Handling of ❤️

### ISSUE THREAD

**Issue by cloudhead** [jameslanska/unicode-display-width#1]
Hey, I'm trying out this crate as a replacement for `unicode-width`, but unfortunately seeing the same problem, which is that `width("❤️")` gives me an answer of `1` instead of `2`, though it is displayed in two columns usually. Is this expected?

**Comment by jameslanska** [comment]
You are absolutely right.  It should have width 2.

The red heart emoji is a very complicated Unicode grapheme.  It is composed of the "Heavy Black Heart" code point U+2764 followed by a "emoji style" variation selector U+FE0F.  The "Heavy Black Heart" code point was added in 1993 with width 1 and was only used in the emoji sequence starting in 2015.

The processing of "emoji style" variation selectors should be fixed in version 0.3.0.

**Comment by cloudhead** [comment]
Ah, that's awesome, thanks!

Yes I learnt a lot about unicode width trying to implement nice tables in the terminal; I ended up hacking around the problem by just filtering out all `U+FE0F` sequences from the output, but it turns red hearts into grey ones.
